"""0001 initial schema

Revision ID: ad7b66d6bff9
Revises: 
Create Date: 2026-05-13 08:06:01.938535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad7b66d6bff9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('semester', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jaccount', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_jaccount'), ['jaccount'], unique=True)

    op.create_table('context_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('router_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_meta', sa.JSON(), nullable=True),
    sa.Column('blob_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blob_hash', sa.LargeBinary(), nullable=True),
    sa.Column('blob_size', sa.BigInteger(), nullable=True),
    sa.Column('blob_status', sa.Enum('pending', 'uploaded', 'verified', 'tampered', 'missing', name='blobstatus'), nullable=False),
    sa.Column('blob_verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_records_blob_status'), ['blob_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_records_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_records_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_records_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_context_records_user_id'), ['user_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('student', 'admin', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.create_table('student_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=True),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_student_tokens_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

    # Partial unique index: at most one active (revoked_at IS NULL) token
    # per user. SQLModel can't express partial uniqueness natively, so we
    # add it explicitly here. Safe on both sqlite and postgres.
    op.create_index(
        'ux_student_tokens_active_per_user',
        'student_tokens',
        ['user_id'],
        unique=True,
        sqlite_where=sa.text('revoked_at IS NULL'),
        postgresql_where=sa.text('revoked_at IS NULL'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ux_student_tokens_active_per_user', table_name='student_tokens')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_tokens_user_id'))
        batch_op.drop_index('ix_student_tokens_user')

    op.drop_table('student_tokens')
    op.drop_table('enrollments')
    with op.batch_alter_table('context_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_context_records_ts'))
        batch_op.drop_index(batch_op.f('ix_context_records_session_id'))
        batch_op.drop_index(batch_op.f('ix_context_records_course_id'))
        batch_op.drop_index(batch_op.f('ix_context_records_blob_status'))

    op.drop_table('context_records')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_jaccount'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_code'))

    op.drop_table('courses')
    # ### end Alembic commands ###
